# Generated by Django 4.0.4 on 2022-05-18 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_walks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='walks',
            options={'ordering': ['-date']},
        ),
    ]
