# Generated by Django 4.0.4 on 2022-05-18 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_walks_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='walks',
            name='dog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.dog'),
        ),
    ]
